name: Deploy
on:
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
    branches:
      - main
  push:
    branches:
      - main
      
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v1
        
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1
        
#       - name: Login to DockerHub
#         uses: docker/login-action@v1 
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
        
#       - name: Build and push
#         uses: docker/build-push-action@v2
#         with:
#           push: true
#           tags: faliqadlan/img-be:latest

      - name: checkout
        uses: actions/checkout@master
      
      - name: login okteto
        uses: okteto/login@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
      
#       - name: "Delete the previews namespace"
#         uses: okteto/delete-namespace@latest
#         with:
#           namespace: mrclinic-faliqadlan
      
      - name: "Create devlopment environments namespace"
        uses: okteto/create-namespace@latest
        with:
          namespace: mrclinic-faliqadlan
      
      - name:  "Activate personal namespace"
        uses: okteto/namespace@latest
        with:
          namespace: mrclinic-faliqadlan
      
      - name: "create deployment"
        uses: okteto/apply@latest
        with:
          namespace: mrclinic-faliqadlan
          manifest: be-deploy.yaml
